META:
  - '/work/pi_mshao_umassd_edu/Iqbal/RadarCLIP/llama_adapter/LLaMA-Adapter/llama_adapter_v2_multimodal7b/data/blip_oneword_labels_all.json'
  - '/work/pi_mshao_umassd_edu/Iqbal/RadarCLIP/llama_adapter/LLaMA-Adapter/llama_adapter_v2_multimodal7b/data/blip_oneword_labels_all.json'
